trigger: none
pr: none

pool:
  name: $(pool.name)
  demands: behind-a-proxy

steps:
  - script: dotnet test simple-test.csproj --logger trx
    env:
      http_proxy: $(Agent.ProxyUrl)
      https_proxy: $(Agent.ProxyUrl)
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
    env:
      http_proxy: $(Agent.ProxyUrl)
      https_proxy: $(Agent.ProxyUrl)
      HTTP_PROXY: $(Agent.ProxyUrl)
      HTTPS_PROXY: $(Agent.ProxyUrl)
